export interface ClubEntry {
  /** Canonical English name, e.g. "Manchester United" */
  en: string;
  /** Hebrew display name, e.g. "מנצ'סטר יונייטד" */
  he: string;
  /** English aliases / nicknames / spelling variants, e.g. ["Man Utd", "Man United"] */
  enAliases: string[];
  /** Hebrew aliases / spelling variants, e.g. ["הפועל פ\"ת", "הפועל פתח תקוה"] */
  heAliases: string[];
}

export const CLUBS: ClubEntry[] = [
  {
    en: "Arsenal",
    he: "ארסנל",
    enAliases: ["Arsenal FC", "The Arsenal", "Gunners"],
    heAliases: [],
  },
  {
    en: "Aston Villa",
    he: "אסטון וילה",
    enAliases: ["Villa", "AVFC", "The Villans"],
    heAliases: [],
  },
  {
    en: "Bournemouth",
    he: "בורנמות'",
    enAliases: ["AFC Bournemouth", "The Cherries", "Boscombe"],
    heAliases: [],
  },
  {
    en: "Brentford",
    he: "ברנטפורד",
    enAliases: ["Brentford FC", "The Bees"],
    heAliases: [],
  },
  {
    en: "Brighton and Hove Albion",
    he: "ברייטון",
    enAliases: ["Brighton", "BHAFC", "The Seagulls"],
    heAliases: ["ברייטון אנד הוב אלביון"],
  },
  {
    en: "Chelsea",
    he: "צ'לסי",
    enAliases: ["Chelsea FC", "The Blues", "CFC"],
    heAliases: [],
  },
  {
    en: "Coventry City",
    he: "קובנטרי סיטי",
    enAliases: ["Coventry", "Sky Blues", "Coventry City FC"],
    heAliases: [],
  },
  {
    en: "Crystal Palace",
    he: "קריסטל פאלאס",
    enAliases: ["Palace", "CPFC", "The Eagles"],
    heAliases: [],
  },
  {
    en: "Everton",
    he: "אברטון",
    enAliases: ["Everton FC", "The Toffees", "EFC"],
    heAliases: [],
  },
  {
    en: "Fulham",
    he: "פולהאם",
    enAliases: ["Fulham FC", "The Cottagers", "FFC"],
    heAliases: [],
  },
  {
    en: "Hull City",
    he: "האל סיטי",
    enAliases: ["Hull", "The Tigers", "Hull City AFC"],
    heAliases: [],
  },
  {
    en: "Ipswich Town",
    he: "איפסוויץ' טאון",
    enAliases: ["Ipswich", "The Tractor Boys", "Ipswich Town FC"],
    heAliases: [],
  },
  {
    en: "Leeds United",
    he: "לידס יונייטד",
    enAliases: ["Leeds", "LUFC", "The Whites"],
    heAliases: [],
  },
  {
    en: "Liverpool",
    he: "ליברפול",
    enAliases: ["Liverpool FC", "The Reds", "LFC"],
    heAliases: [],
  },
  {
    en: "Manchester City",
    he: "מנצ'סטר סיטי",
    enAliases: ["Man City", "City", "MCFC"],
    heAliases: [],
  },
  {
    en: "Manchester United",
    he: "מנצ'סטר יונייטד",
    enAliases: ["Man Utd", "Man United", "United", "MUFC", "Red Devils"],
    heAliases: [],
  },
  {
    en: "Newcastle United",
    he: "ניוקאסל יונייטד",
    enAliases: ["Newcastle", "NUFC", "The Magpies"],
    heAliases: [],
  },
  {
    en: "Nottingham Forest",
    he: "נוטינגהאם פורסט",
    enAliases: ["Forest", "NFFC", "Nottingham Forest FC"],
    heAliases: [],
  },
  {
    en: "Sunderland",
    he: "סנדרלנד",
    enAliases: ["The Black Cats", "SAFC", "Sunderland AFC"],
    heAliases: [],
  },
  {
    en: "Tottenham Hotspur",
    he: "טוטנהאם הוטספר",
    enAliases: ["Spurs", "Tottenham", "THFC"],
    heAliases: [],
  },
  {
    en: "West Ham United",
    he: "ווסטהאם יונייטד",
    enAliases: ["West Ham", "WHUFC", "The Hammers"],
    heAliases: [],
  },
  {
    en: "Wolverhampton Wanderers",
    he: "וולברהמפטון וונדררס",
    enAliases: ["Wolves", "WWFC", "Wolverhampton"],
    heAliases: [],
  },
  {
    en: "Burnley",
    he: "ברנלי",
    enAliases: ["The Clarets", "Burnley FC"],
    heAliases: [],
  },
  {
    en: "Athletic Bilbao",
    he: "אתלטיק בילבאו",
    enAliases: ["Athletic Club", "Athletic", "Athletic de Bilbao"],
    heAliases: [],
  },
  {
    en: "Atlético Madrid",
    he: "אתלטיקו מדריד",
    enAliases: ["Atleti", "Atletico Madrid", "Atlético"],
    heAliases: [],
  },
  {
    en: "Barcelona",
    he: "ברצלונה",
    enAliases: ["Barça", "Barca", "FC Barcelona"],
    heAliases: ["בארסה"],
  },
  {
    en: "Celta Vigo",
    he: "סלטה ויגו",
    enAliases: ["Celta", "RC Celta", "Celta de Vigo"],
    heAliases: [],
  },
  {
    en: "Deportivo Alavés",
    he: "דפורטיבו אלאבס",
    enAliases: ["Alaves", "Alavés", "Deportivo Alaves"],
    heAliases: [],
  },
  {
    en: "Deportivo de A Coruña",
    he: "דפורטיבו לה קורוניה",
    enAliases: ["Deportivo", "Depor", "A Coruña"],
    heAliases: [],
  },
  {
    en: "Elche",
    he: "אלצ'ה",
    enAliases: ["Elche CF", "Elche Club de Fútbol"],
    heAliases: [],
  },
  {
    en: "Espanyol",
    he: "אספניול",
    enAliases: ["RCD Espanyol", "Español", "Pericos"],
    heAliases: [],
  },
  {
    en: "Getafe",
    he: "חטאפה",
    enAliases: ["Getafe CF", "Azulones"],
    heAliases: [],
  },
  {
    en: "Levante",
    he: "לבנטה",
    enAliases: ["Levante UD", "Granotas"],
    heAliases: [],
  },
  {
    en: "Málaga",
    he: "מלאגה",
    enAliases: ["Malaga", "Málaga CF"],
    heAliases: [],
  },
  {
    en: "Racing de Santander",
    he: "ראסינג סנטנדר",
    enAliases: ["Racing", "Real Racing", "Racing Santander", "Real Racing Club", "R. Racing Club"],
    heAliases: [],
  },
  {
    en: "Rayo Vallecano",
    he: "ראיו וייקאנו",
    enAliases: ["Rayo", "Rayo Vallecano de Madrid"],
    heAliases: [],
  },
  {
    en: "Real Betis",
    he: "ריאל בטיס",
    enAliases: ["Betis", "Real Betis Balompié"],
    heAliases: [],
  },
  {
    en: "Real Madrid",
    he: "ריאל מדריד",
    enAliases: ["Real", "Los Blancos", "Real Madrid CF"],
    heAliases: ["ריאל"],
  },
  {
    en: "Real Sociedad",
    he: "ריאל סוסיאדד",
    enAliases: ["La Real", "Sociedad", "Real Sociedad de Fútbol"],
    heAliases: [],
  },
  {
    en: "Sevilla",
    he: "סביליה",
    enAliases: ["Sevilla FC", "Los Rojiblancos"],
    heAliases: [],
  },
  {
    en: "Valencia",
    he: "ולנסיה",
    enAliases: ["Valencia CF", "Los Che"],
    heAliases: [],
  },
  {
    en: "Villarreal",
    he: "ויאריאל",
    enAliases: ["Villarreal CF", "Yellow Submarine"],
    heAliases: [],
  },
  {
    en: "Girona",
    he: "ג'ירונה",
    enAliases: ["Girona FC", "Girona Futbol Club"],
    heAliases: [],
  },
  {
    en: "Mallorca",
    he: "מיורקה",
    enAliases: ["RCD Mallorca", "Los Bermellones"],
    heAliases: [],
  },
  {
    en: "Osasuna",
    he: "אוסאסונה",
    enAliases: ["CA Osasuna", "Los Rojillos"],
    heAliases: [],
  },
  {
    en: "Real Valladolid",
    he: "ריאל ויאדוליד",
    enAliases: ["Valladolid", "Pucela"],
    heAliases: [],
  },
  {
    en: "Las Palmas",
    he: "לאס פאלמאס",
    enAliases: ["UD Las Palmas", "Unión Deportiva Las Palmas"],
    heAliases: [],
  },
  {
    en: "Leganés",
    he: "לגאנס",
    enAliases: ["Leganes", "CD Leganés"],
    heAliases: [],
  },
  {
    en: "Hapoel Petah Tikva",
    he: "הפועל פתח תקווה",
    enAliases: ["Hapoel Petach Tikva"],
    heAliases: ["הפועל פ\"ת", "הפועל פתח תקוה"],
  },
  {
    en: "Hapoel Be'er Sheva",
    he: "הפועל באר שבע",
    enAliases: ["Hapoel Beer Sheva"],
    heAliases: ["הפועל ב\"ש", "הפועל באר-שבע"],
  },
  {
    en: "Maccabi Tel Aviv",
    he: "מכבי תל אביב",
    enAliases: [],
    heAliases: ["מכבי ת\"א"],
  },
  {
    en: "Maccabi Haifa",
    he: "מכבי חיפה",
    enAliases: [],
    heAliases: [],
  },
  {
    en: "Hapoel Jerusalem",
    he: "הפועל ירושלים",
    enAliases: [],
    heAliases: ["הפועל י-ם"],
  },
  {
    en: "Hapoel Ironi Kiryat Shmona",
    he: "הפועל עירוני קריית שמונה",
    enAliases: ["Hapoel Kiryat Shmona"],
    heAliases: ["הפועל קריית שמונה", "הפועל קרית שמונה", "עירוני קריית שמונה", "קריית שמונה", "קרית שמונה"],
  },
  {
    en: "Bnei Sakhnin",
    he: "בני סכנין",
    enAliases: ["Ittihad Bnei Sakhnin"],
    heAliases: ["אתיחאד בני סכנין"],
  },
  {
    en: "Beitar Jerusalem",
    he: "בית\"ר ירושלים",
    enAliases: ["Beitar"],
    heAliases: ["ביתר ירושלים"],
  },
  {
    en: "Hapoel Haifa",
    he: "הפועל חיפה",
    enAliases: [],
    heAliases: [],
  },
  {
    en: "Hapoel Tel Aviv",
    he: "הפועל תל אביב",
    enAliases: [],
    heAliases: [],
  },
  {
    en: "Maccabi Petah Tikva",
    he: "מכבי פתח תקווה",
    enAliases: ["Maccabi Petach Tikva"],
    heAliases: ["מכבי פ\"ת", "מכבי פתח תקוה"],
  },
  {
    en: "Hapoel Ramat Gan",
    he: "הפועל רמת גן",
    enAliases: ["Hapoel Ramat-Gan", "Hapoel Ramat Gan Givataim", "H. Ramat Gan"],
    heAliases: ["הפועל ר\"ג"],
  },
  {
    en: "Ironi Tiberias",
    he: "עירוני טבריה",
    enAliases: ["Hapoel Ironi Tiberias", "Ironi Dorot Tiberias"],
    heAliases: [],
  },
  {
    en: "Maccabi Bnei Reineh",
    he: "מכבי בני ריינה",
    enAliases: ["Maccabi Bnei Raina"],
    heAliases: [],
  },
  {
    en: "Maccabi Netanya",
    he: "מכבי נתניה",
    enAliases: [],
    heAliases: [],
  },
  {
    en: "F.C. Ashdod",
    he: "מ.ס. אשדוד",
    enAliases: ["M.S. Ashdod", "Ashdod"],
    heAliases: ["מועדון ספורט אשדוד", "אשדוד", "מ.ס אשדוד"],
  },
  {
    en: "Bayern Munich",
    he: "באיירן מינכן",
    enAliases: ["Bayern", "FC Bayern", "FC Bayern Munich", "FC Bayern München"],
    heAliases: [],
  },
  {
    en: "Borussia Dortmund",
    he: "בורוסיה דורטמונד",
    enAliases: ["BVB", "Dortmund", "BVB 09"],
    heAliases: [],
  },
  {
    en: "Bayer Leverkusen",
    he: "באייר לברקוזן",
    enAliases: ["Leverkusen", "Bayer 04", "Bayer 04 Leverkusen"],
    heAliases: [],
  },
  {
    en: "Eintracht Frankfurt",
    he: "איינטרכט פרנקפורט",
    enAliases: ["Frankfurt", "Eintracht", "SGE"],
    heAliases: [],
  },
  {
    en: "Paris Saint-Germain",
    he: "פריז סן-ז'רמן",
    enAliases: ["PSG", "Paris SG", "Paris"],
    heAliases: [],
  },
  {
    en: "Marseille",
    he: "מרסיי",
    enAliases: ["Olympique Marseille", "OM"],
    heAliases: [],
  },
  {
    en: "Monaco",
    he: "מונאקו",
    enAliases: ["AS Monaco", "ASM"],
    heAliases: [],
  },
  {
    en: "Inter",
    he: "אינטר",
    enAliases: ["Inter Milan", "Internazionale", "FC Internazionale"],
    heAliases: [],
  },
  {
    en: "AC Milan",
    he: "מילאן",
    enAliases: ["Milan", "Rossoneri"],
    heAliases: [],
  },
  {
    en: "Juventus",
    he: "יובנטוס",
    enAliases: ["Juve", "Juventus FC"],
    heAliases: [],
  },
  {
    en: "Napoli",
    he: "נאפולי",
    enAliases: ["SSC Napoli", "Partenopei"],
    heAliases: [],
  },
  {
    en: "Atalanta",
    he: "אטאלנטה",
    enAliases: ["Atalanta BC", "La Dea"],
    heAliases: [],
  },
  {
    en: "Benfica",
    he: "בנפיקה",
    enAliases: ["SL Benfica", "Águias"],
    heAliases: [],
  },
  {
    en: "Porto",
    he: "פורטו",
    enAliases: ["FC Porto", "Dragões"],
    heAliases: [],
  },
  {
    en: "Sporting CP",
    he: "ספורטינג ליסבון",
    enAliases: ["Sporting", "Sporting Lisbon"],
    heAliases: [],
  },
  {
    en: "Ajax",
    he: "אייאקס",
    enAliases: ["AFC Ajax"],
    heAliases: [],
  },
  {
    en: "PSV Eindhoven",
    he: "פ.ס.וו איינדהובן",
    enAliases: ["PSV"],
    heAliases: [],
  },
  {
    en: "Feyenoord",
    he: "פיינורד",
    enAliases: ["Feyenoord Rotterdam"],
    heAliases: [],
  },
  {
    en: "Club Brugge",
    he: "קלאב ברוז'",
    enAliases: ["Brugge", "Club Brugge KV"],
    heAliases: [],
  },
  {
    en: "Celtic",
    he: "סלטיק",
    enAliases: ["Celtic FC", "The Hoops"],
    heAliases: [],
  },
  {
    en: "Rangers",
    he: "ריינג'רס",
    enAliases: ["Rangers FC", "Gers"],
    heAliases: [],
  },
  {
    en: "Galatasaray",
    he: "גלאטסראיי",
    enAliases: ["Gala", "Galatasaray SK"],
    heAliases: [],
  },
  {
    en: "Fenerbahçe",
    he: "פנרבחצ'ה",
    enAliases: ["Fenerbahce", "Fener"],
    heAliases: [],
  },
  {
    en: "Olympiacos",
    he: "אולימפיאקוס",
    enAliases: ["Olympiacos Piraeus", "Olympiacos FC"],
    heAliases: [],
  },
  {
    en: "Shakhtar Donetsk",
    he: "שחטאר דונייצק",
    enAliases: ["Shakhtar", "FC Shakhtar Donetsk"],
    heAliases: [],
  },
  {
    en: "Dinamo Zagreb",
    he: "דינמו זאגרב",
    enAliases: ["GNK Dinamo", "Dinamo", "GNK Dinamo Zagreb"],
    heAliases: [],
  },
  {
    en: "Red Star Belgrade",
    he: "הכוכב האדום בלגרד",
    enAliases: ["Crvena Zvezda", "Red Star", "FK Crvena Zvezda"],
    heAliases: [],
  },
  {
    en: "RB Salzburg",
    he: "רד בול זלצבורג",
    enAliases: ["Salzburg", "FC Red Bull Salzburg"],
    heAliases: [],
  },
  {
    en: "Sturm Graz",
    he: "שטורם גראץ",
    enAliases: ["SK Sturm", "SK Sturm Graz"],
    heAliases: [],
  },
  {
    en: "Young Boys",
    he: "יאנג בויז",
    enAliases: ["BSC Young Boys", "YB"],
    heAliases: [],
  },
  {
    en: "Sparta Prague",
    he: "ספרטה פראג",
    enAliases: ["AC Sparta", "AC Sparta Praha"],
    heAliases: [],
  },
  {
    en: "Slavia Prague",
    he: "סלביה פראג",
    enAliases: ["SK Slavia", "SK Slavia Praha"],
    heAliases: [],
  },
  {
    en: "FC Copenhagen",
    he: "פ.צ. קופנהגן",
    enAliases: ["FCK", "Copenhagen"],
    heAliases: [],
  },
  {
    en: "Midtjylland",
    he: "מידטיולן",
    enAliases: ["FC Midtjylland", "FCM"],
    heAliases: [],
  },
  {
    en: "Bodø/Glimt",
    he: "בודו גלימט",
    enAliases: ["Bodo Glimt", "Bodø", "FK Bodø/Glimt"],
    heAliases: [],
  },
  {
    en: "Qarabağ",
    he: "קרבאך",
    enAliases: ["Qarabag", "Qarabağ FK"],
    heAliases: [],
  },
  {
    en: "Union Saint-Gilloise",
    he: "אוניון סן-ז'ילואז",
    enAliases: ["Union SG", "USG", "Royale Union Saint-Gilloise"],
    heAliases: [],
  },
  {
    en: "Viktoria Plzeň",
    he: "ויקטוריה פלזן",
    enAliases: ["Viktoria Plzen", "Plzen"],
    heAliases: [],
  },
  {
    en: "Ararat-Armenia",
    he: "ארארט-ארמניה",
    enAliases: ["Ararat Armenia", "FC Ararat-Armenia"],
    heAliases: [],
  },
  {
    en: "Atert Bissen",
    he: "אטרט ביסן",
    enAliases: ["FC Atert Bissen", "Atert"],
    heAliases: [],
  },
  {
    en: "Borac Banja Luka",
    he: "בוראץ באניה לוקה",
    enAliases: ["Borac", "FK Borac"],
    heAliases: [],
  },
  {
    en: "Drita",
    he: "דריטה",
    enAliases: ["FC Drita", "Drita Gjilan"],
    heAliases: [],
  },
  {
    en: "Egnatia",
    he: "אגנטיה",
    enAliases: ["KF Egnatia", "Egnatia Rrogozhinë"],
    heAliases: [],
  },
  {
    en: "Flora Tallinn",
    he: "פלורה טאלין",
    enAliases: ["FC Flora", "Flora"],
    heAliases: [],
  },
  {
    en: "Floriana",
    he: "פלוריאנה",
    enAliases: ["Floriana FC", "The Greens"],
    heAliases: [],
  },
  {
    en: "Győri ETO",
    he: "גיור ETO",
    enAliases: ["Gyori ETO", "ETO FC Győr"],
    heAliases: [],
  },
  {
    en: "Iberia 1999",
    he: "איבריה 1999",
    enAliases: ["FC Iberia 1999", "Iberia"],
    heAliases: [],
  },
  {
    en: "Inter Club d'Escaldes",
    he: "אינטר אסקלדס",
    enAliases: ["Inter Escaldes", "Inter d'Escaldes"],
    heAliases: [],
  },
  {
    en: "Kairat Almaty",
    he: "קאיראט אלמטי",
    enAliases: ["Kairat", "FC Kairat", "FC Kairat Almaty"],
    heAliases: [],
  },
  {
    en: "Kauno Žalgiris",
    he: "קאונו ז'לגיריס",
    enAliases: ["Kauno Zalgiris", "FK Kauno Žalgiris"],
    heAliases: [],
  },
  {
    en: "KuPS",
    he: "קופס",
    enAliases: ["Kuopion Palloseura", "KuPS Kuopio"],
    heAliases: [],
  },
  {
    en: "KÍ Klaksvík",
    he: "קלאקסוויק",
    enAliases: ["KI Klaksvik", "Klaksvik", "Klaksvíkar Ítróttarfelag"],
    heAliases: [],
  },
  {
    en: "Larne",
    he: "לארן",
    enAliases: ["Larne FC", "The Inver Reds"],
    heAliases: [],
  },
  {
    en: "Levski Sofia",
    he: "לבסקי סופיה",
    enAliases: ["Levski", "PFC Levski Sofia"],
    heAliases: [],
  },
  {
    en: "Lincoln Red Imps",
    he: "לינקולן רד אימפס",
    enAliases: ["Lincoln", "Lincoln Red Imps FC"],
    heAliases: [],
  },
  {
    en: "Maxline Vitebsk",
    he: "מקסליין ויטבסק",
    enAliases: ["Maxline", "FC Maxline Vitebsk"],
    heAliases: [],
  },
  {
    en: "Petrocub Hîncești",
    he: "פטרוקוב חינצ'שטי",
    enAliases: ["Petrocub Hincesti", "Petrocub"],
    heAliases: [],
  },
  {
    en: "Riga FC",
    he: "ריגה",
    enAliases: ["Riga", "Riga Football Club"],
    heAliases: [],
  },
  {
    en: "Sabah Baku",
    he: "סבאח באקו",
    enAliases: ["Sabah FK", "Sabah"],
    heAliases: [],
  },
  {
    en: "Shamrock Rovers",
    he: "שאמרוק רוברס",
    enAliases: ["Shamrock", "Rovers"],
    heAliases: [],
  },
  {
    en: "Sutjeska",
    he: "סוטייסקה",
    enAliases: ["FK Sutjeska", "Sutjeska Nikšić"],
    heAliases: [],
  },
  {
    en: "The New Saints",
    he: "דה ניו סיינטס",
    enAliases: ["TNS", "The New Saints FC"],
    heAliases: [],
  },
  {
    en: "Tre Fiori",
    he: "טרה פיורי",
    enAliases: ["SP Tre Fiori", "Tre Fiori FC"],
    heAliases: [],
  },
  {
    en: "Universitatea Craiova",
    he: "אוניברסיטטאה קראיובה",
    enAliases: ["Craiova", "U Craiova"],
    heAliases: [],
  },
  {
    en: "Vardar",
    he: "ורדאר",
    enAliases: ["FK Vardar", "FK Vardar Skopje"],
    heAliases: [],
  },
  {
    en: "Víkingur Reykjavík",
    he: "ויקינגור רייקיאוויק",
    enAliases: ["Vikingur Reykjavik", "Víkingur"],
    heAliases: [],
  },
  // --- Sofascore spelling coverage (added 2026-09-15) ---
  {
    en: "Olympique Lyonnais",
    he: "אולימפיק ליון",
    enAliases: ["Olympique Lyon", "Lyon", "OL"],
    heAliases: [],
  },
  {
    en: "ŠK Slovan Bratislava",
    he: "סלובן ברטיסלבה",
    enAliases: ["Slovan Bratislava", "Slovan"],
    heAliases: [],
  },
  {
    en: "NK Celje",
    he: "צליה",
    enAliases: ["Celje"],
    heAliases: [],
  },
  {
    en: "NEC Nijmegen",
    he: "ניימכן",
    enAliases: ["NEC", "N.E.C. Nijmegen"],
    heAliases: [],
  },
  {
    en: "LASK",
    he: "לאסק",
    enAliases: ["LASK Linz"],
    heAliases: [],
  },
  {
    en: "AEK Athens",
    he: "א.א.ק אתונה",
    enAliases: ["AEK", "AEK Athen"],
    heAliases: [],
  },
  {
    en: "Viking FK",
    he: "ויקינג סטוונגר",
    enAliases: ["Viking", "Viking Stavanger"],
    heAliases: [],
  },
  {
    en: "Lille",
    he: "ליל",
    enAliases: ["LOSC Lille", "LOSC"],
    heAliases: [],
  },
  {
    en: "VfB Stuttgart",
    he: "שטוטגרט",
    enAliases: ["Stuttgart", "VfB"],
    heAliases: [],
  },
  {
    en: "AS Roma",
    he: "רומא",
    enAliases: ["Roma"],
    heAliases: [],
  },
  {
    en: "RC Lens",
    he: "לאנס",
    enAliases: ["Lens", "Racing Lens"],
    heAliases: [],
  },
  {
    en: "Como",
    he: "קומו",
    enAliases: ["Como 1907"],
    heAliases: [],
  },
  {
    en: "RB Leipzig",
    he: "ר.ב. לייפציג",
    enAliases: ["Leipzig", "RasenBallsport Leipzig"],
    heAliases: [],
  },
  {
    en: "Omonia Nicosia",
    he: "אומוניה ניקוסיה",
    enAliases: ["Omonia", "AC Omonia"],
    heAliases: [],
  },
  {
    en: "Lech Poznań",
    he: "לך פוזנן",
    enAliases: ["Lech", "Lech Poznan", "KKS Lech Poznań"],
    heAliases: [],
  },
  {
    en: "AGF",
    he: "אורהוס",
    enAliases: ["AGF Aarhus", "Aarhus GF"],
    heAliases: [],
  },
  {
    en: "Górnik Zabrze",
    he: "גורניק זאבז'ה",
    enAliases: ["Gornik Zabrze", "Górnik"],
    heAliases: [],
  },
  {
    en: "Mjällby AIF",
    he: "מיאלבי",
    enAliases: ["Mjallby AIF", "Mjällby"],
    heAliases: [],
  },
];
